name: Build and Test App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Test React App
      run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build Spring Boot App
      run: ./mvnw clean install

    - name: Test Spring Boot App
      run: ./mvnw test
